// AUTO-GENERATED from Guangna_Languo_Colors_Sorted_Volg.xlsx (manually curated color-group
// sheets: name, code, and hue heuristics considered, then hand-adjusted for a smooth,
// visually logical light-to-dark order within each family -- NOT a pure luminance sort.
// Supersedes the older lib/guangnaColorGroups.ts (Guangna-only, computed order).
// Regenerate whenever the master color-groups spreadsheet changes -- do not hand-edit.

export type ColorFamily =
  | 'white-grey-black'
  | 'brown'
  | 'pink'
  | 'red'
  | 'orange'
  | 'yellow'
  | 'green'
  | 'blue'
  | 'violet-purple';

export const COLOR_FAMILY_LABELS: Record<ColorFamily, string> = {
  'white-grey-black': 'White / Grey / Black',
  'brown': 'Brown / Earth',
  'pink': 'Pink',
  'red': 'Red',
  'orange': 'Orange',
  'yellow': 'Yellow',
  'green': 'Green',
  'blue': 'Blue',
  'violet-purple': 'Violet / purple',
};

export interface FamilyMembership {
  family: ColorFamily;
  order: number; // manually curated position within the family, light to dark
}

export type ColorSource = 'guangna' | 'languo';

export interface ColorFamilyEntry {
  code: string;
  source: ColorSource;
  memberships: FamilyMembership[];
}

// Keyed by code (e.g. 'GN-761' or 'AG-171') for O(1) lookup.
export const COLOR_FAMILIES: Record<string, ColorFamilyEntry> = {
  'GN-600': { code: 'GN-600', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 1 }] },
  'GN-601': { code: 'GN-601', source: 'guangna', memberships: [{ family: 'blue', order: 61 }] },
  'GN-602': { code: 'GN-602', source: 'guangna', memberships: [{ family: 'green', order: 71 }, { family: 'blue', order: 30 }] },
  'GN-603': { code: 'GN-603', source: 'guangna', memberships: [{ family: 'yellow', order: 25 }] },
  'GN-604': { code: 'GN-604', source: 'guangna', memberships: [{ family: 'orange', order: 42 }] },
  'GN-605': { code: 'GN-605', source: 'guangna', memberships: [{ family: 'red', order: 36 }] },
  'GN-606': { code: 'GN-606', source: 'guangna', memberships: [{ family: 'pink', order: 80 }, { family: 'red', order: 13 }, { family: 'violet-purple', order: 40 }] },
  'GN-607': { code: 'GN-607', source: 'guangna', memberships: [{ family: 'violet-purple', order: 64 }] },
  'GN-608': { code: 'GN-608', source: 'guangna', memberships: [{ family: 'blue', order: 112 }] },
  'GN-609': { code: 'GN-609', source: 'guangna', memberships: [{ family: 'green', order: 110 }] },
  'GN-610': { code: 'GN-610', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 68 }] },
  'GN-611': { code: 'GN-611', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 112 }] },
  'GN-612': { code: 'GN-612', source: 'guangna', memberships: [{ family: 'pink', order: 60 }] },
  'GN-613': { code: 'GN-613', source: 'guangna', memberships: [{ family: 'violet-purple', order: 59 }] },
  'GN-614': { code: 'GN-614', source: 'guangna', memberships: [{ family: 'green', order: 58 }] },
  'GN-615': { code: 'GN-615', source: 'guangna', memberships: [{ family: 'yellow', order: 28 }] },
  'GN-616': { code: 'GN-616', source: 'guangna', memberships: [{ family: 'blue', order: 79 }] },
  'GN-617': { code: 'GN-617', source: 'guangna', memberships: [{ family: 'blue', order: 110 }] },
  'GN-618': { code: 'GN-618', source: 'guangna', memberships: [{ family: 'brown', order: 42 }, { family: 'orange', order: 41 }] },
  'GN-619': { code: 'GN-619', source: 'guangna', memberships: [{ family: 'brown', order: 53 }, { family: 'pink', order: 77 }] },
  'GN-620': { code: 'GN-620', source: 'guangna', memberships: [{ family: 'brown', order: 78 }] },
  'GN-621': { code: 'GN-621', source: 'guangna', memberships: [{ family: 'blue', order: 70 }] },
  'GN-622': { code: 'GN-622', source: 'guangna', memberships: [{ family: 'green', order: 76 }, { family: 'blue', order: 71 }] },
  'GN-623': { code: 'GN-623', source: 'guangna', memberships: [{ family: 'violet-purple', order: 27 }] },
  'GN-624': { code: 'GN-624', source: 'guangna', memberships: [{ family: 'pink', order: 16 }] },
  'GN-625': { code: 'GN-625', source: 'guangna', memberships: [{ family: 'pink', order: 28 }, { family: 'orange', order: 23 }] },
  'GN-626': { code: 'GN-626', source: 'guangna', memberships: [{ family: 'yellow', order: 10 }] },
  'GN-627': { code: 'GN-627', source: 'guangna', memberships: [{ family: 'green', order: 29 }] },
  'GN-628': { code: 'GN-628', source: 'guangna', memberships: [{ family: 'blue', order: 12 }] },
  'GN-629': { code: 'GN-629', source: 'guangna', memberships: [{ family: 'violet-purple', order: 18 }] },
  'GN-630': { code: 'GN-630', source: 'guangna', memberships: [{ family: 'brown', order: 18 }, { family: 'pink', order: 30 }] },
  'GN-631': { code: 'GN-631', source: 'guangna', memberships: [{ family: 'brown', order: 92 }, { family: 'red', order: 41 }, { family: 'orange', order: 51 }] },
  'GN-632': { code: 'GN-632', source: 'guangna', memberships: [{ family: 'red', order: 39 }, { family: 'orange', order: 49 }] },
  'GN-633': { code: 'GN-633', source: 'guangna', memberships: [{ family: 'blue', order: 57 }] },
  'GN-634': { code: 'GN-634', source: 'guangna', memberships: [{ family: 'green', order: 100 }] },
  'GN-635': { code: 'GN-635', source: 'guangna', memberships: [{ family: 'violet-purple', order: 19 }] },
  'GN-636': { code: 'GN-636', source: 'guangna', memberships: [{ family: 'blue', order: 91 }] },
  'GN-637': { code: 'GN-637', source: 'guangna', memberships: [{ family: 'green', order: 53 }] },
  'GN-638': { code: 'GN-638', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 58 }, { family: 'green', order: 16 }] },
  'GN-639': { code: 'GN-639', source: 'guangna', memberships: [{ family: 'brown', order: 50 }, { family: 'red', order: 9 }] },
  'GN-640': { code: 'GN-640', source: 'guangna', memberships: [{ family: 'green', order: 66 }] },
  'GN-641': { code: 'GN-641', source: 'guangna', memberships: [{ family: 'green', order: 52 }] },
  'GN-642': { code: 'GN-642', source: 'guangna', memberships: [{ family: 'green', order: 123 }] },
  'GN-643': { code: 'GN-643', source: 'guangna', memberships: [{ family: 'brown', order: 95 }] },
  'GN-644': { code: 'GN-644', source: 'guangna', memberships: [{ family: 'brown', order: 51 }] },
  'GN-645': { code: 'GN-645', source: 'guangna', memberships: [{ family: 'orange', order: 24 }, { family: 'yellow', order: 36 }, { family: 'brown', order: 14.5 }] },
  'GN-646': { code: 'GN-646', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 36 }] },
  'GN-647': { code: 'GN-647', source: 'guangna', memberships: [{ family: 'green', order: 62 }] },
  'GN-648': { code: 'GN-648', source: 'guangna', memberships: [{ family: 'green', order: 36 }] },
  'GN-649': { code: 'GN-649', source: 'guangna', memberships: [{ family: 'orange', order: 38 }] },
  'GN-650': { code: 'GN-650', source: 'guangna', memberships: [{ family: 'blue', order: 69 }] },
  'GN-651': { code: 'GN-651', source: 'guangna', memberships: [{ family: 'blue', order: 54 }, { family: 'violet-purple', order: 32 }] },
  'GN-652': { code: 'GN-652', source: 'guangna', memberships: [{ family: 'green', order: 39 }] },
  'GN-653': { code: 'GN-653', source: 'guangna', memberships: [{ family: 'green', order: 78 }, { family: 'blue', order: 52 }] },
  'GN-654': { code: 'GN-654', source: 'guangna', memberships: [{ family: 'brown', order: 31 }, { family: 'pink', order: 47 }] },
  'GN-655': { code: 'GN-655', source: 'guangna', memberships: [{ family: 'pink', order: 61 }] },
  'GN-656': { code: 'GN-656', source: 'guangna', memberships: [{ family: 'brown', order: 17 }, { family: 'orange', order: 25 }, { family: 'yellow', order: 31 }] },
  'GN-657': { code: 'GN-657', source: 'guangna', memberships: [{ family: 'green', order: 88 }] },
  'GN-658': { code: 'GN-658', source: 'guangna', memberships: [{ family: 'pink', order: 53 }, { family: 'violet-purple', order: 15.5 }] },
  'GN-659': { code: 'GN-659', source: 'guangna', memberships: [{ family: 'blue', order: 89 }] },
  'GN-660': { code: 'GN-660', source: 'guangna', memberships: [{ family: 'pink', order: 74 }] },
  'GN-661': { code: 'GN-661', source: 'guangna', memberships: [{ family: 'pink', order: 82 }, { family: 'red', order: 19 }] },
  'GN-662': { code: 'GN-662', source: 'guangna', memberships: [{ family: 'green', order: 60 }] },
  'GN-663': { code: 'GN-663', source: 'guangna', memberships: [{ family: 'red', order: 22 }, { family: 'orange', order: 45 }] },
  'GN-664': { code: 'GN-664', source: 'guangna', memberships: [{ family: 'red', order: 32 }] },
  'GN-665': { code: 'GN-665', source: 'guangna', memberships: [{ family: 'green', order: 90 }] },
  'GN-666': { code: 'GN-666', source: 'guangna', memberships: [{ family: 'pink', order: 102 }, { family: 'red', order: 17 }, { family: 'violet-purple', order: 44 }] },
  'GN-667': { code: 'GN-667', source: 'guangna', memberships: [{ family: 'pink', order: 86 }, { family: 'red', order: 20 }] },
  'GN-668': { code: 'GN-668', source: 'guangna', memberships: [{ family: 'green', order: 96 }] },
  'GN-669': { code: 'GN-669', source: 'guangna', memberships: [{ family: 'green', order: 44 }] },
  'GN-670': { code: 'GN-670', source: 'guangna', memberships: [{ family: 'blue', order: 55 }] },
  'GN-671': { code: 'GN-671', source: 'guangna', memberships: [{ family: 'pink', order: 112 }, { family: 'red', order: 45 }] },
  'GN-672': { code: 'GN-672', source: 'guangna', memberships: [{ family: 'brown', order: 99 }, { family: 'red', order: 50 }] },
  'GN-673': { code: 'GN-673', source: 'guangna', memberships: [{ family: 'blue', order: 116 }] },
  'GN-674': { code: 'GN-674', source: 'guangna', memberships: [{ family: 'brown', order: 103 }, { family: 'red', order: 51 }] },
  'GN-675': { code: 'GN-675', source: 'guangna', memberships: [{ family: 'violet-purple', order: 58 }] },
  'GN-676': { code: 'GN-676', source: 'guangna', memberships: [{ family: 'green', order: 103 }] },
  'GN-677': { code: 'GN-677', source: 'guangna', memberships: [{ family: 'pink', order: 50 }, { family: 'red', order: 6 }] },
  'GN-678': { code: 'GN-678', source: 'guangna', memberships: [{ family: 'blue', order: 117 }, { family: 'violet-purple', order: 68 }] },
  'GN-679': { code: 'GN-679', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 92 }, { family: 'red', order: 60 }] },
  'GN-680': { code: 'GN-680', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 106 }] },
  'GN-681': { code: 'GN-681', source: 'guangna', memberships: [{ family: 'blue', order: 47 }] },
  'GN-682': { code: 'GN-682', source: 'guangna', memberships: [{ family: 'green', order: 93 }] },
  'GN-683': { code: 'GN-683', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 22 }, { family: 'orange', order: 11 }] },
  'GN-684': { code: 'GN-684', source: 'guangna', memberships: [{ family: 'orange', order: 26 }, { family: 'yellow', order: 32 }] },
  'GN-685': { code: 'GN-685', source: 'guangna', memberships: [{ family: 'green', order: 69 }] },
  'GN-686': { code: 'GN-686', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 50 }] },
  'GN-687': { code: 'GN-687', source: 'guangna', memberships: [{ family: 'green', order: 94 }] },
  'GN-688': { code: 'GN-688', source: 'guangna', memberships: [{ family: 'blue', order: 113 }] },
  'GN-689': { code: 'GN-689', source: 'guangna', memberships: [{ family: 'blue', order: 34 }] },
  'GN-690': { code: 'GN-690', source: 'guangna', memberships: [{ family: 'green', order: 74 }, { family: 'blue', order: 56 }] },
  'GN-691': { code: 'GN-691', source: 'guangna', memberships: [{ family: 'pink', order: 73 }, { family: 'red', order: 18.5 }] },
  'GN-692': { code: 'GN-692', source: 'guangna', memberships: [{ family: 'pink', order: 69 }, { family: 'violet-purple', order: 39 }] },
  'GN-693': { code: 'GN-693', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 89 }, { family: 'blue', order: 82 }] },
  'GN-694': { code: 'GN-694', source: 'guangna', memberships: [{ family: 'green', order: 115 }] },
  'GN-695': { code: 'GN-695', source: 'guangna', memberships: [{ family: 'green', order: 111 }, { family: 'blue', order: 84 }] },
  'GN-696': { code: 'GN-696', source: 'guangna', memberships: [{ family: 'green', order: 91 }] },
  'GN-697': { code: 'GN-697', source: 'guangna', memberships: [{ family: 'green', order: 125 }] },
  'GN-698': { code: 'GN-698', source: 'guangna', memberships: [{ family: 'violet-purple', order: 11 }] },
  'GN-699': { code: 'GN-699', source: 'guangna', memberships: [{ family: 'violet-purple', order: 26 }] },
  'GN-700': { code: 'GN-700', source: 'guangna', memberships: [{ family: 'yellow', order: 42 }, { family: 'green', order: 24 }] },
  'GN-701': { code: 'GN-701', source: 'guangna', memberships: [{ family: 'orange', order: 13 }] },
  'GN-702': { code: 'GN-702', source: 'guangna', memberships: [{ family: 'orange', order: 27 }] },
  'GN-703': { code: 'GN-703', source: 'guangna', memberships: [{ family: 'pink', order: 12 }, { family: 'orange', order: 12 }] },
  'GN-704': { code: 'GN-704', source: 'guangna', memberships: [{ family: 'pink', order: 41 }, { family: 'red', order: 3 }] },
  'GN-705': { code: 'GN-705', source: 'guangna', memberships: [{ family: 'red', order: 47 }, { family: 'violet-purple', order: 57 }] },
  'GN-706': { code: 'GN-706', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 18 }, { family: 'green', order: 4 }, { family: 'blue', order: 1 }] },
  'GN-707': { code: 'GN-707', source: 'guangna', memberships: [{ family: 'green', order: 13 }] },
  'GN-708': { code: 'GN-708', source: 'guangna', memberships: [{ family: 'brown', order: 110 }] },
  'GN-709': { code: 'GN-709', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 105 }, { family: 'brown', order: 118 }] },
  'GN-710': { code: 'GN-710', source: 'guangna', memberships: [{ family: 'pink', order: 95 }, { family: 'red', order: 26 }] },
  'GN-711': { code: 'GN-711', source: 'guangna', memberships: [{ family: 'pink', order: 88 }] },
  'GN-712': { code: 'GN-712', source: 'guangna', memberships: [{ family: 'pink', order: 62 }] },
  'GN-713': { code: 'GN-713', source: 'guangna', memberships: [{ family: 'pink', order: 93 }, { family: 'red', order: 15 }] },
  'GN-714': { code: 'GN-714', source: 'guangna', memberships: [{ family: 'pink', order: 110 }] },
  'GN-715': { code: 'GN-715', source: 'guangna', memberships: [{ family: 'pink', order: 108 }, { family: 'red', order: 31 }] },
  'GN-716': { code: 'GN-716', source: 'guangna', memberships: [{ family: 'pink', order: 35 }] },
  'GN-717': { code: 'GN-717', source: 'guangna', memberships: [{ family: 'brown', order: 14 }, { family: 'orange', order: 20 }] },
  'GN-718': { code: 'GN-718', source: 'guangna', memberships: [{ family: 'brown', order: 8 }, { family: 'orange', order: 16 }] },
  'GN-719': { code: 'GN-719', source: 'guangna', memberships: [{ family: 'orange', order: 9 }, { family: 'yellow', order: 7 }] },
  'GN-720': { code: 'GN-720', source: 'guangna', memberships: [{ family: 'brown', order: 2 }, { family: 'orange', order: 10 }, { family: 'yellow', order: 6 }] },
  'GN-721': { code: 'GN-721', source: 'guangna', memberships: [{ family: 'pink', order: 9 }] },
  'GN-722': { code: 'GN-722', source: 'guangna', memberships: [{ family: 'blue', order: 53 }] },
  'GN-723': { code: 'GN-723', source: 'guangna', memberships: [{ family: 'pink', order: 11 }] },
  'GN-724': { code: 'GN-724', source: 'guangna', memberships: [{ family: 'brown', order: 1 }, { family: 'orange', order: 8 }] },
  'GN-725': { code: 'GN-725', source: 'guangna', memberships: [{ family: 'orange', order: 43 }] },
  'GN-726': { code: 'GN-726', source: 'guangna', memberships: [{ family: 'violet-purple', order: 46 }, { family: 'pink', order: 106.5 }] },
  'GN-727': { code: 'GN-727', source: 'guangna', memberships: [{ family: 'green', order: 55 }] },
  'GN-728': { code: 'GN-728', source: 'guangna', memberships: [{ family: 'green', order: 99 }] },
  'GN-729': { code: 'GN-729', source: 'guangna', memberships: [{ family: 'yellow', order: 39 }] },
  'GN-730': { code: 'GN-730', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 24 }, { family: 'green', order: 6 }] },
  'GN-731': { code: 'GN-731', source: 'guangna', memberships: [{ family: 'brown', order: 28 }] },
  'GN-732': { code: 'GN-732', source: 'guangna', memberships: [{ family: 'yellow', order: 14 }] },
  'GN-733': { code: 'GN-733', source: 'guangna', memberships: [{ family: 'yellow', order: 17 }] },
  'GN-734': { code: 'GN-734', source: 'guangna', memberships: [{ family: 'pink', order: 39 }, { family: 'violet-purple', order: 13 }] },
  'GN-735': { code: 'GN-735', source: 'guangna', memberships: [{ family: 'green', order: 57 }] },
  'GN-736': { code: 'GN-736', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 27 }, { family: 'blue', order: 6 }] },
  'GN-737': { code: 'GN-737', source: 'guangna', memberships: [{ family: 'green', order: 46 }, { family: 'blue', order: 26 }] },
  'GN-738': { code: 'GN-738', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 35 }] },
  'GN-739': { code: 'GN-739', source: 'guangna', memberships: [{ family: 'violet-purple', order: 48 }] },
  'GN-740': { code: 'GN-740', source: 'guangna', memberships: [{ family: 'green', order: 97 }] },
  'GN-741': { code: 'GN-741', source: 'guangna', memberships: [{ family: 'green', order: 65 }] },
  'GN-742': { code: 'GN-742', source: 'guangna', memberships: [{ family: 'violet-purple', order: 49 }] },
  'GN-743': { code: 'GN-743', source: 'guangna', memberships: [{ family: 'violet-purple', order: 55 }] },
  'GN-744': { code: 'GN-744', source: 'guangna', memberships: [{ family: 'violet-purple', order: 8 }] },
  'GN-745': { code: 'GN-745', source: 'guangna', memberships: [{ family: 'blue', order: 35 }] },
  'GN-746': { code: 'GN-746', source: 'guangna', memberships: [{ family: 'blue', order: 114 }] },
  'GN-747': { code: 'GN-747', source: 'guangna', memberships: [{ family: 'blue', order: 72 }] },
  'GN-748': { code: 'GN-748', source: 'guangna', memberships: [{ family: 'blue', order: 76 }] },
  'GN-749': { code: 'GN-749', source: 'guangna', memberships: [{ family: 'blue', order: 75 }] },
  'GN-750': { code: 'GN-750', source: 'guangna', memberships: [{ family: 'blue', order: 74 }] },
  'GN-751': { code: 'GN-751', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 37 }] },
  'GN-752': { code: 'GN-752', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 55 }, { family: 'pink', order: 31 }, { family: 'violet-purple', order: 10 }] },
  'GN-753': { code: 'GN-753', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 57 }, { family: 'brown', order: 25 }, { family: 'green', order: 20 }] },
  'GN-754': { code: 'GN-754', source: 'guangna', memberships: [{ family: 'brown', order: 24 }, { family: 'pink', order: 33 }, { family: 'violet-purple', order: 10.6 }] },
  'GN-755': { code: 'GN-755', source: 'guangna', memberships: [{ family: 'pink', order: 67 }, { family: 'red', order: 8 }] },
  'GN-756': { code: 'GN-756', source: 'guangna', memberships: [{ family: 'brown', order: 59 }, { family: 'red', order: 10 }] },
  'GN-757': { code: 'GN-757', source: 'guangna', memberships: [{ family: 'brown', order: 55 }] },
  'GN-758': { code: 'GN-758', source: 'guangna', memberships: [{ family: 'brown', order: 68 }] },
  'GN-759': { code: 'GN-759', source: 'guangna', memberships: [{ family: 'brown', order: 85 }, { family: 'yellow', order: 64 }] },
  'GN-760': { code: 'GN-760', source: 'guangna', memberships: [{ family: 'red', order: 33 }] },
  'GN-761': { code: 'GN-761', source: 'guangna', memberships: [{ family: 'pink', order: 78 }] },
  'GN-762': { code: 'GN-762', source: 'guangna', memberships: [{ family: 'pink', order: 66 }] },
  'GN-763': { code: 'GN-763', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 111 }, { family: 'blue', order: 118 }] },
  'GN-764': { code: 'GN-764', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 104 }, { family: 'violet-purple', order: 66 }] },
  'GN-765': { code: 'GN-765', source: 'guangna', memberships: [{ family: 'yellow', order: 23 }] },
  'GN-766': { code: 'GN-766', source: 'guangna', memberships: [{ family: 'yellow', order: 13 }] },
  'GN-767': { code: 'GN-767', source: 'guangna', memberships: [{ family: 'blue', order: 73 }] },
  'GN-768': { code: 'GN-768', source: 'guangna', memberships: [{ family: 'blue', order: 41 }] },
  'GN-769': { code: 'GN-769', source: 'guangna', memberships: [{ family: 'brown', order: 98 }] },
  'GN-770': { code: 'GN-770', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 84 }, { family: 'violet-purple', order: 37 }] },
  'GN-771': { code: 'GN-771', source: 'guangna', memberships: [{ family: 'brown', order: 20 }, { family: 'violet-purple', order: 10.4 }] },
  'GN-772': { code: 'GN-772', source: 'guangna', memberships: [{ family: 'pink', order: 76 }] },
  'GN-773': { code: 'GN-773', source: 'guangna', memberships: [{ family: 'violet-purple', order: 31 }] },
  'GN-774': { code: 'GN-774', source: 'guangna', memberships: [{ family: 'blue', order: 106 }] },
  'GN-775': { code: 'GN-775', source: 'guangna', memberships: [{ family: 'green', order: 50 }] },
  'GN-776': { code: 'GN-776', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 108 }, { family: 'brown', order: 121 }] },
  'GN-777': { code: 'GN-777', source: 'guangna', memberships: [{ family: 'yellow', order: 19 }] },
  'GN-778': { code: 'GN-778', source: 'guangna', memberships: [{ family: 'violet-purple', order: 62 }] },
  'GN-779': { code: 'GN-779', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 96 }, { family: 'brown', order: 106 }, { family: 'violet-purple', order: 64.5 }] },
  'GN-780': { code: 'GN-780', source: 'guangna', memberships: [{ family: 'brown', order: 107 }, { family: 'red', order: 52 }] },
  'GN-781': { code: 'GN-781', source: 'guangna', memberships: [{ family: 'brown', order: 115 }, { family: 'red', order: 57 }] },
  'GN-782': { code: 'GN-782', source: 'guangna', memberships: [{ family: 'red', order: 29 }] },
  'GN-783': { code: 'GN-783', source: 'guangna', memberships: [{ family: 'red', order: 28 }, { family: 'orange', order: 48 }] },
  'GN-784': { code: 'GN-784', source: 'guangna', memberships: [{ family: 'brown', order: 120 }, { family: 'red', order: 59 }] },
  'GN-785': { code: 'GN-785', source: 'guangna', memberships: [{ family: 'red', order: 40 }, { family: 'orange', order: 50 }] },
  'GN-786': { code: 'GN-786', source: 'guangna', memberships: [{ family: 'orange', order: 34 }, { family: 'yellow', order: 54 }] },
  'GN-787': { code: 'GN-787', source: 'guangna', memberships: [{ family: 'yellow', order: 45 }, { family: 'green', order: 40 }] },
  'GN-788': { code: 'GN-788', source: 'guangna', memberships: [{ family: 'yellow', order: 62 }, { family: 'green', order: 63 }] },
  'GN-789': { code: 'GN-789', source: 'guangna', memberships: [{ family: 'brown', order: 105 }, { family: 'green', order: 128 }] },
  'GN-790': { code: 'GN-790', source: 'guangna', memberships: [{ family: 'green', order: 121 }] },
  'GN-791': { code: 'GN-791', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 107 }, { family: 'green', order: 127 }] },
  'GN-792': { code: 'GN-792', source: 'guangna', memberships: [{ family: 'green', order: 106 }, { family: 'blue', order: 81 }] },
  'GN-793': { code: 'GN-793', source: 'guangna', memberships: [{ family: 'green', order: 118 }] },
  'GN-794': { code: 'GN-794', source: 'guangna', memberships: [{ family: 'green', order: 104 }] },
  'GN-795': { code: 'GN-795', source: 'guangna', memberships: [{ family: 'green', order: 117 }] },
  'GN-796': { code: 'GN-796', source: 'guangna', memberships: [{ family: 'green', order: 116 }, { family: 'blue', order: 94 }] },
  'GN-797': { code: 'GN-797', source: 'guangna', memberships: [{ family: 'green', order: 114 }, { family: 'blue', order: 93 }] },
  'GN-798': { code: 'GN-798', source: 'guangna', memberships: [{ family: 'blue', order: 88 }] },
  'GN-799': { code: 'GN-799', source: 'guangna', memberships: [{ family: 'green', order: 80 }, { family: 'blue', order: 77 }] },
  'GN-800': { code: 'GN-800', source: 'guangna', memberships: [{ family: 'green', order: 113 }] },
  'GN-801': { code: 'GN-801', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 20 }] },
  'GN-802': { code: 'GN-802', source: 'guangna', memberships: [{ family: 'orange', order: 31 }, { family: 'yellow', order: 52 }] },
  'GN-803': { code: 'GN-803', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 32 }] },
  'GN-804': { code: 'GN-804', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 44 }] },
  'GN-805': { code: 'GN-805', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 75 }] },
  'GN-806': { code: 'GN-806', source: 'guangna', memberships: [{ family: 'red', order: 61 }, { family: 'blue', order: 99 }] },
  'GN-807': { code: 'GN-807', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 109 }] },
  'GN-808': { code: 'GN-808', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 102 }, { family: 'violet-purple', order: 65 }] },
  'GN-809': { code: 'GN-809', source: 'guangna', memberships: [{ family: 'green', order: 9 }] },
  'GN-810': { code: 'GN-810', source: 'guangna', memberships: [{ family: 'brown', order: 32 }, { family: 'yellow', order: 47 }, { family: 'green', order: 38 }] },
  'GN-811': { code: 'GN-811', source: 'guangna', memberships: [{ family: 'brown', order: 39 }, { family: 'yellow', order: 51 }] },
  'GN-812': { code: 'GN-812', source: 'guangna', memberships: [{ family: 'brown', order: 58 }, { family: 'green', order: 86 }] },
  'GN-813': { code: 'GN-813', source: 'guangna', memberships: [{ family: 'brown', order: 45 }, { family: 'yellow', order: 59 }, { family: 'green', order: 85 }] },
  'GN-814': { code: 'GN-814', source: 'guangna', memberships: [{ family: 'brown', order: 44 }, { family: 'yellow', order: 57 }] },
  'GN-815': { code: 'GN-815', source: 'guangna', memberships: [{ family: 'brown', order: 41 }] },
  'GN-816': { code: 'GN-816', source: 'guangna', memberships: [{ family: 'brown', order: 76 }] },
  'GN-817': { code: 'GN-817', source: 'guangna', memberships: [{ family: 'brown', order: 65 }, { family: 'yellow', order: 63 }] },
  'GN-818': { code: 'GN-818', source: 'guangna', memberships: [{ family: 'blue', order: 11 }] },
  'GN-819': { code: 'GN-819', source: 'guangna', memberships: [{ family: 'blue', order: 27 }] },
  'GN-820': { code: 'GN-820', source: 'guangna', memberships: [{ family: 'blue', order: 49 }] },
  'GN-821': { code: 'GN-821', source: 'guangna', memberships: [{ family: 'blue', order: 9 }] },
  'GN-822': { code: 'GN-822', source: 'guangna', memberships: [{ family: 'blue', order: 24 }] },
  'GN-823': { code: 'GN-823', source: 'guangna', memberships: [{ family: 'blue', order: 59 }] },
  'GN-824': { code: 'GN-824', source: 'guangna', memberships: [{ family: 'blue', order: 111 }] },
  'GN-825': { code: 'GN-825', source: 'guangna', memberships: [{ family: 'violet-purple', order: 7 }] },
  'GN-826': { code: 'GN-826', source: 'guangna', memberships: [{ family: 'violet-purple', order: 20 }] },
  'GN-827': { code: 'GN-827', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 83 }, { family: 'violet-purple', order: 36 }] },
  'GN-828': { code: 'GN-828', source: 'guangna', memberships: [{ family: 'violet-purple', order: 50 }] },
  'GN-829': { code: 'GN-829', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 51 }] },
  'GN-830': { code: 'GN-830', source: 'guangna', memberships: [{ family: 'blue', order: 20 }, { family: 'violet-purple', order: 17 }] },
  'GN-831': { code: 'GN-831', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 78 }, { family: 'violet-purple', order: 34 }] },
  'GN-832': { code: 'GN-832', source: 'guangna', memberships: [{ family: 'violet-purple', order: 53 }] },
  'GN-833': { code: 'GN-833', source: 'guangna', memberships: [{ family: 'violet-purple', order: 35 }] },
  'GN-834': { code: 'GN-834', source: 'guangna', memberships: [{ family: 'pink', order: 24 }] },
  'GN-835': { code: 'GN-835', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 54 }, { family: 'pink', order: 32 }, { family: 'violet-purple', order: 9 }] },
  'GN-836': { code: 'GN-836', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 9 }, { family: 'pink', order: 2 }] },
  'GN-837': { code: 'GN-837', source: 'guangna', memberships: [{ family: 'pink', order: 7 }] },
  'GN-838': { code: 'GN-838', source: 'guangna', memberships: [{ family: 'pink', order: 14 }] },
  'GN-839': { code: 'GN-839', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 56 }, { family: 'pink', order: 49 }] },
  'GN-840': { code: 'GN-840', source: 'guangna', memberships: [{ family: 'pink', order: 26 }] },
  'GN-841': { code: 'GN-841', source: 'guangna', memberships: [{ family: 'blue', order: 13 }] },
  'GN-842': { code: 'GN-842', source: 'guangna', memberships: [{ family: 'blue', order: 25 }] },
  'GN-843': { code: 'GN-843', source: 'guangna', memberships: [{ family: 'blue', order: 16 }] },
  'GN-844': { code: 'GN-844', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 71 }, { family: 'blue', order: 37 }] },
  'GN-845': { code: 'GN-845', source: 'guangna', memberships: [{ family: 'green', order: 95 }] },
  'GN-846': { code: 'GN-846', source: 'guangna', memberships: [{ family: 'green', order: 67 }] },
  'GN-847': { code: 'GN-847', source: 'guangna', memberships: [{ family: 'yellow', order: 44 }, { family: 'green', order: 35 }] },
  'GN-848': { code: 'GN-848', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 47 }, { family: 'green', order: 15 }] },
  'GN-849': { code: 'GN-849', source: 'guangna', memberships: [{ family: 'green', order: 84 }] },
  'GN-850': { code: 'GN-850', source: 'guangna', memberships: [{ family: 'blue', order: 28 }] },
  'GN-851': { code: 'GN-851', source: 'guangna', memberships: [{ family: 'green', order: 18 }] },
  'GN-852': { code: 'GN-852', source: 'guangna', memberships: [{ family: 'green', order: 64 }] },
  'GN-853': { code: 'GN-853', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 42 }] },
  'GN-854': { code: 'GN-854', source: 'guangna', memberships: [{ family: 'pink', order: 65 }] },
  'GN-855': { code: 'GN-855', source: 'guangna', memberships: [{ family: 'yellow', order: 41 }] },
  'GN-856': { code: 'GN-856', source: 'guangna', memberships: [{ family: 'green', order: 25 }] },
  'GN-857': { code: 'GN-857', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 76 }, { family: 'blue', order: 46 }] },
  'GN-858': { code: 'GN-858', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 62 }, { family: 'green', order: 37 }] },
  'GN-859': { code: 'GN-859', source: 'guangna', memberships: [{ family: 'orange', order: 40 }] },
  'GN-860': { code: 'GN-860', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 87 }] },
  'GN-861': { code: 'GN-861', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 63 }] },
  'GN-862': { code: 'GN-862', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 39 }, { family: 'pink', order: 29 }, { family: 'violet-purple', order: 5 }] },
  'GN-863': { code: 'GN-863', source: 'guangna', memberships: [{ family: 'brown', order: 86 }] },
  'GN-864': { code: 'GN-864', source: 'guangna', memberships: [{ family: 'brown', order: 104 }] },
  'GN-865': { code: 'GN-865', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 86 }, { family: 'brown', order: 81 }] },
  'GN-866': { code: 'GN-866', source: 'guangna', memberships: [{ family: 'brown', order: 93 }] },
  'GN-867': { code: 'GN-867', source: 'guangna', memberships: [{ family: 'brown', order: 116 }] },
  'GN-868': { code: 'GN-868', source: 'guangna', memberships: [{ family: 'brown', order: 47 }] },
  'GN-869': { code: 'GN-869', source: 'guangna', memberships: [{ family: 'brown', order: 84 }] },
  'GN-870': { code: 'GN-870', source: 'guangna', memberships: [{ family: 'brown', order: 62 }] },
  'GN-871': { code: 'GN-871', source: 'guangna', memberships: [{ family: 'brown', order: 7 }] },
  'GN-872': { code: 'GN-872', source: 'guangna', memberships: [{ family: 'pink', order: 34 }, { family: 'red', order: 2 }] },
  'GN-873': { code: 'GN-873', source: 'guangna', memberships: [{ family: 'pink', order: 19 }] },
  'GN-874': { code: 'GN-874', source: 'guangna', memberships: [{ family: 'brown', order: 11 }, { family: 'yellow', order: 38 }] },
  'GN-875': { code: 'GN-875', source: 'guangna', memberships: [{ family: 'brown', order: 94 }] },
  'GN-876': { code: 'GN-876', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 26 }, { family: 'green', order: 10 }] },
  'GN-877': { code: 'GN-877', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 10 }, { family: 'orange', order: 3 }, { family: 'yellow', order: 4 }] },
  'GN-878': { code: 'GN-878', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 30 }, { family: 'blue', order: 8 }] },
  'GN-879': { code: 'GN-879', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 29 }, { family: 'violet-purple', order: 6 }] },
  'GN-880': { code: 'GN-880', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 28 }, { family: 'violet-purple', order: 2 }] },
  'GN-881': { code: 'GN-881', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 21 }, { family: 'pink', order: 10 }] },
  'GN-882': { code: 'GN-882', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 19 }, { family: 'pink', order: 4 }, { family: 'orange', order: 7 }] },
  'GN-883': { code: 'GN-883', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 6 }, { family: 'orange', order: 1 }, { family: 'yellow', order: 1 }] },
  'GN-884': { code: 'GN-884', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 34 }, { family: 'blue', order: 4 }] },
  'GN-885': { code: 'GN-885', source: 'guangna', memberships: [{ family: 'green', order: 32 }, { family: 'blue', order: 15 }] },
  'GN-886': { code: 'GN-886', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 23 }, { family: 'green', order: 5 }] },
  'GN-887': { code: 'GN-887', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 16 }, { family: 'yellow', order: 8 }] },
  'GN-888': { code: 'GN-888', source: 'guangna', memberships: [{ family: 'blue', order: 33 }] },
  'GN-889': { code: 'GN-889', source: 'guangna', memberships: [{ family: 'blue', order: 32 }] },
  'GN-890': { code: 'GN-890', source: 'guangna', memberships: [{ family: 'blue', order: 50 }] },
  'GN-891': { code: 'GN-891', source: 'guangna', memberships: [{ family: 'blue', order: 60 }] },
  'GN-892': { code: 'GN-892', source: 'guangna', memberships: [{ family: 'blue', order: 62 }] },
  'GN-893': { code: 'GN-893', source: 'guangna', memberships: [{ family: 'blue', order: 66 }] },
  'GN-894': { code: 'GN-894', source: 'guangna', memberships: [{ family: 'blue', order: 68 }] },
  'GN-895': { code: 'GN-895', source: 'guangna', memberships: [{ family: 'blue', order: 90 }] },
  'GN-896': { code: 'GN-896', source: 'guangna', memberships: [{ family: 'blue', order: 95 }] },
  'GN-897': { code: 'GN-897', source: 'guangna', memberships: [{ family: 'blue', order: 115 }] },
  'GN-898': { code: 'GN-898', source: 'guangna', memberships: [{ family: 'blue', order: 17 }] },
  'GN-899': { code: 'GN-899', source: 'guangna', memberships: [{ family: 'blue', order: 43 }, { family: 'violet-purple', order: 28 }] },
  'GN-900': { code: 'GN-900', source: 'guangna', memberships: [{ family: 'violet-purple', order: 38 }] },
  'GN-901': { code: 'GN-901', source: 'guangna', memberships: [{ family: 'blue', order: 109 }] },
  'GN-902': { code: 'GN-902', source: 'guangna', memberships: [{ family: 'violet-purple', order: 67 }] },
  'GN-903': { code: 'GN-903', source: 'guangna', memberships: [{ family: 'pink', order: 18 }, { family: 'red', order: 1 }] },
  'GN-904': { code: 'GN-904', source: 'guangna', memberships: [{ family: 'pink', order: 81 }, { family: 'red', order: 12 }] },
  'GN-905': { code: 'GN-905', source: 'guangna', memberships: [{ family: 'pink', order: 85 }] },
  'GN-906': { code: 'GN-906', source: 'guangna', memberships: [{ family: 'pink', order: 106 }, { family: 'red', order: 18 }, { family: 'violet-purple', order: 45 }] },
  'GN-907': { code: 'GN-907', source: 'guangna', memberships: [{ family: 'pink', order: 111 }, { family: 'red', order: 34 }] },
  'GN-908': { code: 'GN-908', source: 'guangna', memberships: [{ family: 'pink', order: 91 }, { family: 'red', order: 14 }] },
  'GN-909': { code: 'GN-909', source: 'guangna', memberships: [{ family: 'red', order: 16 }, { family: 'violet-purple', order: 42 }, { family: 'pink', order: 95.5 }] },
  'GN-910': { code: 'GN-910', source: 'guangna', memberships: [{ family: 'pink', order: 103 }, { family: 'red', order: 37 }] },
  'GN-911': { code: 'GN-911', source: 'guangna', memberships: [{ family: 'orange', order: 17 }] },
  'GN-912': { code: 'GN-912', source: 'guangna', memberships: [{ family: 'pink', order: 21 }, { family: 'orange', order: 22 }] },
  'GN-913': { code: 'GN-913', source: 'guangna', memberships: [{ family: 'pink', order: 48 }] },
  'GN-914': { code: 'GN-914', source: 'guangna', memberships: [{ family: 'orange', order: 18 }] },
  'GN-915': { code: 'GN-915', source: 'guangna', memberships: [{ family: 'brown', order: 33 }, { family: 'pink', order: 55 }] },
  'GN-916': { code: 'GN-916', source: 'guangna', memberships: [{ family: 'brown', order: 35 }, { family: 'red', order: 7 }, { family: 'orange', order: 37 }] },
  'GN-917': { code: 'GN-917', source: 'guangna', memberships: [{ family: 'pink', order: 15 }] },
  'GN-918': { code: 'GN-918', source: 'guangna', memberships: [{ family: 'pink', order: 43 }, { family: 'red', order: 5 }] },
  'GN-919': { code: 'GN-919', source: 'guangna', memberships: [{ family: 'pink', order: 90 }, { family: 'red', order: 11 }] },
  'GN-920': { code: 'GN-920', source: 'guangna', memberships: [{ family: 'pink', order: 100 }, { family: 'red', order: 43 }] },
  'GN-921': { code: 'GN-921', source: 'guangna', memberships: [{ family: 'brown', order: 79 }, { family: 'red', order: 42 }] },
  'GN-922': { code: 'GN-922', source: 'guangna', memberships: [{ family: 'red', order: 46 }] },
  'GN-923': { code: 'GN-923', source: 'guangna', memberships: [{ family: 'brown', order: 114 }, { family: 'red', order: 56 }] },
  'GN-924': { code: 'GN-924', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 12 }] },
  'GN-925': { code: 'GN-925', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 25 }, { family: 'brown', order: 5 }, { family: 'green', order: 11 }] },
  'GN-926': { code: 'GN-926', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 45 }, { family: 'brown', order: 13 }, { family: 'orange', order: 19 }] },
  'GN-927': { code: 'GN-927', source: 'guangna', memberships: [{ family: 'brown', order: 26 }] },
  'GN-928': { code: 'GN-928', source: 'guangna', memberships: [{ family: 'brown', order: 38 }] },
  'GN-929': { code: 'GN-929', source: 'guangna', memberships: [{ family: 'brown', order: 16 }, { family: 'orange', order: 21 }] },
  'GN-930': { code: 'GN-930', source: 'guangna', memberships: [{ family: 'orange', order: 36 }] },
  'GN-931': { code: 'GN-931', source: 'guangna', memberships: [{ family: 'brown', order: 63 }, { family: 'orange', order: 46 }] },
  'GN-932': { code: 'GN-932', source: 'guangna', memberships: [{ family: 'brown', order: 72 }] },
  'GN-933': { code: 'GN-933', source: 'guangna', memberships: [{ family: 'yellow', order: 20 }] },
  'GN-934': { code: 'GN-934', source: 'guangna', memberships: [{ family: 'yellow', order: 33 }] },
  'GN-935': { code: 'GN-935', source: 'guangna', memberships: [{ family: 'orange', order: 33 }] },
  'GN-936': { code: 'GN-936', source: 'guangna', memberships: [{ family: 'orange', order: 32 }] },
  'GN-937': { code: 'GN-937', source: 'guangna', memberships: [{ family: 'orange', order: 44 }] },
  'GN-938': { code: 'GN-938', source: 'guangna', memberships: [{ family: 'yellow', order: 46 }, { family: 'green', order: 56 }] },
  'GN-939': { code: 'GN-939', source: 'guangna', memberships: [{ family: 'green', order: 34 }] },
  'GN-940': { code: 'GN-940', source: 'guangna', memberships: [{ family: 'green', order: 31 }] },
  'GN-941': { code: 'GN-941', source: 'guangna', memberships: [{ family: 'green', order: 102 }] },
  'GN-942': { code: 'GN-942', source: 'guangna', memberships: [{ family: 'green', order: 105 }] },
  'GN-943': { code: 'GN-943', source: 'guangna', memberships: [{ family: 'brown', order: 46 }, { family: 'yellow', order: 60 }, { family: 'green', order: 84.5 }] },
  'GN-944': { code: 'GN-944', source: 'guangna', memberships: [{ family: 'brown', order: 64 }, { family: 'green', order: 87 }] },
  'GN-945': { code: 'GN-945', source: 'guangna', memberships: [{ family: 'brown', order: 102 }, { family: 'green', order: 123.5 }] },
  'GN-946': { code: 'GN-946', source: 'guangna', memberships: [{ family: 'brown', order: 87 }, { family: 'green', order: 120 }] },
  'GN-947': { code: 'GN-947', source: 'guangna', memberships: [{ family: 'brown', order: 97 }] },
  'GN-948': { code: 'GN-948', source: 'guangna', memberships: [{ family: 'brown', order: 108 }, { family: 'green', order: 129 }] },
  'GN-949': { code: 'GN-949', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 38 }] },
  'GN-950': { code: 'GN-950', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 59 }] },
  'GN-951': { code: 'GN-951', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 67 }] },
  'GN-952': { code: 'GN-952', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 74 }] },
  'GN-953': { code: 'GN-953', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 81 }] },
  'GN-954': { code: 'GN-954', source: 'guangna', memberships: [{ family: 'blue', order: 42 }] },
  'GN-955': { code: 'GN-955', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 46 }, { family: 'green', order: 14 }] },
  'GN-956': { code: 'GN-956', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 61 }] },
  'GN-957': { code: 'GN-957', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 69 }] },
  'GN-958': { code: 'GN-958', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 82 }, { family: 'brown', order: 69 }] },
  'GN-959': { code: 'GN-959', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 88 }] },
  'GN-960': { code: 'GN-960', source: 'guangna', memberships: [{ family: 'brown', order: 82 }] },
  'GN-961': { code: 'GN-961', source: 'guangna', memberships: [{ family: 'white-grey-black', order: 64 }, { family: 'green', order: 51 }] },
  'GN-962': { code: 'GN-962', source: 'guangna', memberships: [{ family: 'violet-purple', order: 25 }] },
  'GN-963': { code: 'GN-963', source: 'guangna', memberships: [{ family: 'brown', order: 119 }, { family: 'red', order: 58 }] },
  'GN-964': { code: 'GN-964', source: 'guangna', memberships: [{ family: 'brown', order: 73 }] },
  'GN-965': { code: 'GN-965', source: 'guangna', memberships: [{ family: 'pink', order: 42 }, { family: 'red', order: 4 }] },
  'AG-171': { code: 'AG-171', source: 'languo', memberships: [{ family: 'white-grey-black', order: 49 }] },
  'AG-172': { code: 'AG-172', source: 'languo', memberships: [{ family: 'white-grey-black', order: 60 }] },
  'AG-173': { code: 'AG-173', source: 'languo', memberships: [{ family: 'white-grey-black', order: 52 }] },
  'AG-174': { code: 'AG-174', source: 'languo', memberships: [{ family: 'white-grey-black', order: 66 }, { family: 'green', order: 19 }] },
  'AG-175': { code: 'AG-175', source: 'languo', memberships: [{ family: 'white-grey-black', order: 73 }] },
  'AG-176': { code: 'AG-176', source: 'languo', memberships: [{ family: 'white-grey-black', order: 77 }] },
  'AG-177': { code: 'AG-177', source: 'languo', memberships: [{ family: 'brown', order: 27 }] },
  'AG-178': { code: 'AG-178', source: 'languo', memberships: [{ family: 'brown', order: 36 }] },
  'AG-179': { code: 'AG-179', source: 'languo', memberships: [{ family: 'brown', order: 57 }] },
  'AG-245': { code: 'AG-245', source: 'languo', memberships: [{ family: 'brown', order: 12 }] },
  'AG-246': { code: 'AG-246', source: 'languo', memberships: [{ family: 'brown', order: 9 }] },
  'AG-247': { code: 'AG-247', source: 'languo', memberships: [{ family: 'brown', order: 23 }] },
  'AG-248': { code: 'AG-248', source: 'languo', memberships: [{ family: 'brown', order: 48 }] },
  'AG-249': { code: 'AG-249', source: 'languo', memberships: [{ family: 'brown', order: 21 }] },
  'AG-250': { code: 'AG-250', source: 'languo', memberships: [{ family: 'brown', order: 37 }] },
  'AG-251': { code: 'AG-251', source: 'languo', memberships: [{ family: 'brown', order: 60 }] },
  'AG-252': { code: 'AG-252', source: 'languo', memberships: [{ family: 'brown', order: 77 }, { family: 'green', order: 119 }] },
  'AG-253': { code: 'AG-253', source: 'languo', memberships: [{ family: 'brown', order: 71 }] },
  'AG-254': { code: 'AG-254', source: 'languo', memberships: [{ family: 'brown', order: 67 }] },
  'AG-255': { code: 'AG-255', source: 'languo', memberships: [{ family: 'white-grey-black', order: 80 }] },
  'AG-256': { code: 'AG-256', source: 'languo', memberships: [{ family: 'brown', order: 80 }] },
  'BL-201': { code: 'BL-201', source: 'languo', memberships: [{ family: 'blue', order: 7 }] },
  'BL-202': { code: 'BL-202', source: 'languo', memberships: [{ family: 'blue', order: 22 }] },
  'BL-203': { code: 'BL-203', source: 'languo', memberships: [{ family: 'blue', order: 29 }] },
  'BL-204': { code: 'BL-204', source: 'languo', memberships: [{ family: 'blue', order: 10 }] },
  'BL-205': { code: 'BL-205', source: 'languo', memberships: [{ family: 'blue', order: 23 }] },
  'BL-206': { code: 'BL-206', source: 'languo', memberships: [{ family: 'blue', order: 51 }] },
  'BL-207': { code: 'BL-207', source: 'languo', memberships: [{ family: 'blue', order: 97 }] },
  'BL-208': { code: 'BL-208', source: 'languo', memberships: [{ family: 'blue', order: 83 }] },
  'BL-209': { code: 'BL-209', source: 'languo', memberships: [{ family: 'blue', order: 107 }] },
  'BL-210': { code: 'BL-210', source: 'languo', memberships: [{ family: 'blue', order: 63 }] },
  'BL-211': { code: 'BL-211', source: 'languo', memberships: [{ family: 'blue', order: 64 }] },
  'BL-212': { code: 'BL-212', source: 'languo', memberships: [{ family: 'blue', order: 87 }] },
  'BL-213': { code: 'BL-213', source: 'languo', memberships: [{ family: 'blue', order: 65 }] },
  'BL-214': { code: 'BL-214', source: 'languo', memberships: [{ family: 'blue', order: 80 }] },
  'BL-215': { code: 'BL-215', source: 'languo', memberships: [{ family: 'blue', order: 67 }] },
  'BL-257': { code: 'BL-257', source: 'languo', memberships: [{ family: 'blue', order: 3 }] },
  'BL-258': { code: 'BL-258', source: 'languo', memberships: [{ family: 'blue', order: 5 }] },
  'BL-259': { code: 'BL-259', source: 'languo', memberships: [{ family: 'blue', order: 19 }] },
  'BL-260': { code: 'BL-260', source: 'languo', memberships: [{ family: 'blue', order: 36 }] },
  'BL-261': { code: 'BL-261', source: 'languo', memberships: [{ family: 'blue', order: 45 }] },
  'BL-262': { code: 'BL-262', source: 'languo', memberships: [{ family: 'blue', order: 101 }] },
  'BL-263': { code: 'BL-263', source: 'languo', memberships: [{ family: 'blue', order: 102 }] },
  'BL-264': { code: 'BL-264', source: 'languo', memberships: [{ family: 'blue', order: 103 }] },
  'BL-265': { code: 'BL-265', source: 'languo', memberships: [{ family: 'blue', order: 104 }] },
  'BL-266': { code: 'BL-266', source: 'languo', memberships: [{ family: 'blue', order: 98 }] },
  'BL-267': { code: 'BL-267', source: 'languo', memberships: [{ family: 'blue', order: 105 }] },
  'BL-268': { code: 'BL-268', source: 'languo', memberships: [{ family: 'blue', order: 86 }] },
  'BR-701': { code: 'BR-701', source: 'languo', memberships: [{ family: 'brown', order: 3 }] },
  'BR-702': { code: 'BR-702', source: 'languo', memberships: [{ family: 'brown', order: 10 }] },
  'BR-703': { code: 'BR-703', source: 'languo', memberships: [{ family: 'brown', order: 19 }] },
  'BR-704': { code: 'BR-704', source: 'languo', memberships: [{ family: 'brown', order: 22 }] },
  'BR-705': { code: 'BR-705', source: 'languo', memberships: [{ family: 'brown', order: 52 }] },
  'BR-706': { code: 'BR-706', source: 'languo', memberships: [{ family: 'brown', order: 54 }] },
  'BR-707': { code: 'BR-707', source: 'languo', memberships: [{ family: 'brown', order: 91 }] },
  'BR-708': { code: 'BR-708', source: 'languo', memberships: [{ family: 'brown', order: 100 }] },
  'BR-709': { code: 'BR-709', source: 'languo', memberships: [{ family: 'brown', order: 109 }] },
  'BR-710': { code: 'BR-710', source: 'languo', memberships: [{ family: 'white-grey-black', order: 31 }, { family: 'brown', order: 4 }] },
  'BR-711': { code: 'BR-711', source: 'languo', memberships: [{ family: 'brown', order: 30 }] },
  'BR-712': { code: 'BR-712', source: 'languo', memberships: [{ family: 'brown', order: 15 }] },
  'BR-713': { code: 'BR-713', source: 'languo', memberships: [{ family: 'brown', order: 43 }] },
  'BR-714': { code: 'BR-714', source: 'languo', memberships: [{ family: 'brown', order: 70 }] },
  'BR-715': { code: 'BR-715', source: 'languo', memberships: [{ family: 'brown', order: 83 }] },
  'CB-901': { code: 'CB-901', source: 'languo', memberships: [{ family: 'white-grey-black', order: 94 }] },
  'CB-902': { code: 'CB-902', source: 'languo', memberships: [{ family: 'white-grey-black', order: 103 }, { family: 'blue', order: 100 }] },
  'CB-903': { code: 'CB-903', source: 'languo', memberships: [{ family: 'white-grey-black', order: 93 }] },
  'CB-904': { code: 'CB-904', source: 'languo', memberships: [{ family: 'white-grey-black', order: 97 }] },
  'CB-905': { code: 'CB-905', source: 'languo', memberships: [{ family: 'white-grey-black', order: 90 }] },
  'CB-906': { code: 'CB-906', source: 'languo', memberships: [{ family: 'white-grey-black', order: 98 }, { family: 'brown', order: 117 }] },
  'CB-907': { code: 'CB-907', source: 'languo', memberships: [{ family: 'white-grey-black', order: 101 }] },
  'CB-908': { code: 'CB-908', source: 'languo', memberships: [{ family: 'white-grey-black', order: 100 }, { family: 'blue', order: 108 }, { family: 'violet-purple', order: 61 }] },
  'CB-909': { code: 'CB-909', source: 'languo', memberships: [{ family: 'white-grey-black', order: 91 }] },
  'CB-910': { code: 'CB-910', source: 'languo', memberships: [{ family: 'white-grey-black', order: 95 }] },
  'CS-141': { code: 'CS-141', source: 'languo', memberships: [{ family: 'yellow', order: 15 }] },
  'CS-142': { code: 'CS-142', source: 'languo', memberships: [{ family: 'orange', order: 4 }] },
  'CS-143': { code: 'CS-143', source: 'languo', memberships: [{ family: 'pink', order: 23 }] },
  'CS-144': { code: 'CS-144', source: 'languo', memberships: [{ family: 'orange', order: 5 }] },
  'CS-145': { code: 'CS-145', source: 'languo', memberships: [{ family: 'brown', order: 6 }] },
  'CS-146': { code: 'CS-146', source: 'languo', memberships: [{ family: 'pink', order: 17 }] },
  'CS-147': { code: 'CS-147', source: 'languo', memberships: [{ family: 'pink', order: 36 }] },
  'CS-148': { code: 'CS-148', source: 'languo', memberships: [{ family: 'brown', order: 40 }] },
  'CS-149': { code: 'CS-149', source: 'languo', memberships: [{ family: 'brown', order: 61 }] },
  'CS-501': { code: 'CS-501', source: 'languo', memberships: [{ family: 'white-grey-black', order: 4 }] },
  'CS-502': { code: 'CS-502', source: 'languo', memberships: [{ family: 'pink', order: 5 }] },
  'CS-503': { code: 'CS-503', source: 'languo', memberships: [{ family: 'yellow', order: 3 }] },
  'CS-504': { code: 'CS-504', source: 'languo', memberships: [{ family: 'orange', order: 14 }] },
  'CS-505': { code: 'CS-505', source: 'languo', memberships: [{ family: 'orange', order: 6 }] },
  'CS-506': { code: 'CS-506', source: 'languo', memberships: [{ family: 'orange', order: 15 }] },
  'CS-507': { code: 'CS-507', source: 'languo', memberships: [{ family: 'pink', order: 54 }] },
  'CS-508': { code: 'CS-508', source: 'languo', memberships: [{ family: 'pink', order: 51 }] },
  'CS-509': { code: 'CS-509', source: 'languo', memberships: [{ family: 'brown', order: 34 }] },
  'CS-510': { code: 'CS-510', source: 'languo', memberships: [{ family: 'yellow', order: 5 }] },
  'CS-511': { code: 'CS-511', source: 'languo', memberships: [{ family: 'orange', order: 28 }] },
  'DB-161': { code: 'DB-161', source: 'languo', memberships: [{ family: 'blue', order: 14 }] },
  'DB-1610': { code: 'DB-1610', source: 'languo', memberships: [{ family: 'blue', order: 44 }] },
  'DB-1611': { code: 'DB-1611', source: 'languo', memberships: [{ family: 'blue', order: 40 }] },
  'DB-1612': { code: 'DB-1612', source: 'languo', memberships: [{ family: 'blue', order: 48 }] },
  'DB-162': { code: 'DB-162', source: 'languo', memberships: [{ family: 'blue', order: 18 }] },
  'DB-163': { code: 'DB-163', source: 'languo', memberships: [{ family: 'blue', order: 38 }] },
  'DB-164': { code: 'DB-164', source: 'languo', memberships: [{ family: 'blue', order: 39 }] },
  'DB-165': { code: 'DB-165', source: 'languo', memberships: [{ family: 'blue', order: 58 }] },
  'DB-166': { code: 'DB-166', source: 'languo', memberships: [{ family: 'blue', order: 78 }] },
  'DB-167': { code: 'DB-167', source: 'languo', memberships: [{ family: 'blue', order: 85 }] },
  'DB-168': { code: 'DB-168', source: 'languo', memberships: [{ family: 'blue', order: 92 }] },
  'DB-169': { code: 'DB-169', source: 'languo', memberships: [{ family: 'blue', order: 96 }] },
  'DS-181': { code: 'DS-181', source: 'languo', memberships: [{ family: 'brown', order: 29 }, { family: 'orange', order: 29 }] },
  'DS-182': { code: 'DS-182', source: 'languo', memberships: [{ family: 'brown', order: 56 }] },
  'DS-183': { code: 'DS-183', source: 'languo', memberships: [{ family: 'brown', order: 75 }] },
  'DS-184': { code: 'DS-184', source: 'languo', memberships: [{ family: 'brown', order: 96 }] },
  'DS-185': { code: 'DS-185', source: 'languo', memberships: [{ family: 'brown', order: 66 }] },
  'DS-186': { code: 'DS-186', source: 'languo', memberships: [{ family: 'brown', order: 49 }] },
  'DS-187': { code: 'DS-187', source: 'languo', memberships: [{ family: 'brown', order: 74 }] },
  'DS-188': { code: 'DS-188', source: 'languo', memberships: [{ family: 'brown', order: 88 }] },
  'DS-189': { code: 'DS-189', source: 'languo', memberships: [{ family: 'brown', order: 101 }] },
  'GB-401': { code: 'GB-401', source: 'languo', memberships: [{ family: 'white-grey-black', order: 2 }] },
  'GB-402': { code: 'GB-402', source: 'languo', memberships: [{ family: 'white-grey-black', order: 41 }] },
  'GB-403': { code: 'GB-403', source: 'languo', memberships: [{ family: 'white-grey-black', order: 65 }] },
  'GB-404': { code: 'GB-404', source: 'languo', memberships: [{ family: 'white-grey-black', order: 79 }] },
  'GB-405': { code: 'GB-405', source: 'languo', memberships: [{ family: 'white-grey-black', order: 110 }] },
  'GB-406': { code: 'GB-406', source: 'languo', memberships: [{ family: 'white-grey-black', order: 85 }] },
  'GB-407': { code: 'GB-407', source: 'languo', memberships: [{ family: 'white-grey-black', order: 72 }] },
  'GB-408': { code: 'GB-408', source: 'languo', memberships: [{ family: 'white-grey-black', order: 48 }] },
  'GB-409': { code: 'GB-409', source: 'languo', memberships: [{ family: 'white-grey-black', order: 33 }] },
  'GB-410': { code: 'GB-410', source: 'languo', memberships: [{ family: 'white-grey-black', order: 43 }] },
  'GB-411': { code: 'GB-411', source: 'languo', memberships: [{ family: 'white-grey-black', order: 70 }] },
  'GB-412': { code: 'GB-412', source: 'languo', memberships: [{ family: 'white-grey-black', order: 99 }] },
  'GR-101': { code: 'GR-101', source: 'languo', memberships: [{ family: 'green', order: 3 }] },
  'GR-1010': { code: 'GR-1010', source: 'languo', memberships: [{ family: 'green', order: 77 }] },
  'GR-1011': { code: 'GR-1011', source: 'languo', memberships: [{ family: 'green', order: 41 }] },
  'GR-1012': { code: 'GR-1012', source: 'languo', memberships: [{ family: 'green', order: 33 }] },
  'GR-1013': { code: 'GR-1013', source: 'languo', memberships: [{ family: 'green', order: 72 }] },
  'GR-102': { code: 'GR-102', source: 'languo', memberships: [{ family: 'green', order: 7 }] },
  'GR-103': { code: 'GR-103', source: 'languo', memberships: [{ family: 'green', order: 30 }] },
  'GR-104': { code: 'GR-104', source: 'languo', memberships: [{ family: 'green', order: 22 }] },
  'GR-105': { code: 'GR-105', source: 'languo', memberships: [{ family: 'green', order: 54 }] },
  'GR-106': { code: 'GR-106', source: 'languo', memberships: [{ family: 'green', order: 61 }] },
  'GR-107': { code: 'GR-107', source: 'languo', memberships: [{ family: 'green', order: 81 }] },
  'GR-108': { code: 'GR-108', source: 'languo', memberships: [{ family: 'green', order: 109 }] },
  'GR-109': { code: 'GR-109', source: 'languo', memberships: [{ family: 'green', order: 107 }] },
  'GR-110': { code: 'GR-110', source: 'languo', memberships: [{ family: 'green', order: 8 }] },
  'GR-111': { code: 'GR-111', source: 'languo', memberships: [{ family: 'green', order: 43 }] },
  'GR-112': { code: 'GR-112', source: 'languo', memberships: [{ family: 'green', order: 82 }] },
  'GR-113': { code: 'GR-113', source: 'languo', memberships: [{ family: 'green', order: 98 }] },
  'GR-114': { code: 'GR-114', source: 'languo', memberships: [{ family: 'green', order: 79 }] },
  'GR-115': { code: 'GR-115', source: 'languo', memberships: [{ family: 'green', order: 112 }] },
  'HC-131': { code: 'HC-131', source: 'languo', memberships: [{ family: 'green', order: 47 }] },
  'HC-132': { code: 'HC-132', source: 'languo', memberships: [{ family: 'green', order: 42 }] },
  'HC-133': { code: 'HC-133', source: 'languo', memberships: [{ family: 'green', order: 21 }] },
  'HC-134': { code: 'HC-134', source: 'languo', memberships: [{ family: 'yellow', order: 24 }] },
  'HC-135': { code: 'HC-135', source: 'languo', memberships: [{ family: 'orange', order: 35 }] },
  'HC-136': { code: 'HC-136', source: 'languo', memberships: [{ family: 'pink', order: 59 }] },
  'HC-137': { code: 'HC-137', source: 'languo', memberships: [{ family: 'violet-purple', order: 23 }] },
  'HC-138': { code: 'HC-138', source: 'languo', memberships: [{ family: 'blue', order: 21 }] },
  'HC-139': { code: 'HC-139', source: 'languo', memberships: [{ family: 'pink', order: 71 }] },
  'HC-601': { code: 'HC-601', source: 'languo', memberships: [{ family: 'pink', order: 22 }] },
  'HC-602': { code: 'HC-602', source: 'languo', memberships: [{ family: 'yellow', order: 22 }] },
  'HC-603': { code: 'HC-603', source: 'languo', memberships: [{ family: 'green', order: 26 }] },
  'HC-604': { code: 'HC-604', source: 'languo', memberships: [{ family: 'blue', order: 31 }] },
  'HC-605': { code: 'HC-605', source: 'languo', memberships: [{ family: 'violet-purple', order: 30 }] },
  'HC-606': { code: 'HC-606', source: 'languo', memberships: [{ family: 'orange', order: 30 }] },
  'HC-607': { code: 'HC-607', source: 'languo', memberships: [{ family: 'pink', order: 44 }] },
  'HC-608': { code: 'HC-608', source: 'languo', memberships: [{ family: 'yellow', order: 48 }] },
  'HC-609': { code: 'HC-609', source: 'languo', memberships: [{ family: 'white-grey-black', order: 53 }] },
  'LC-111': { code: 'LC-111', source: 'languo', memberships: [{ family: 'pink', order: 25 }] },
  'LC-1110': { code: 'LC-1110', source: 'languo', memberships: [{ family: 'white-grey-black', order: 40 }] },
  'LC-112': { code: 'LC-112', source: 'languo', memberships: [{ family: 'pink', order: 68 }] },
  'LC-113': { code: 'LC-113', source: 'languo', memberships: [{ family: 'red', order: 24 }] },
  'LC-114': { code: 'LC-114', source: 'languo', memberships: [{ family: 'red', order: 35 }] },
  'LC-115': { code: 'LC-115', source: 'languo', memberships: [{ family: 'pink', order: 52 }] },
  'LC-116': { code: 'LC-116', source: 'languo', memberships: [{ family: 'pink', order: 75 }] },
  'LC-117': { code: 'LC-117', source: 'languo', memberships: [{ family: 'pink', order: 72 }] },
  'LC-118': { code: 'LC-118', source: 'languo', memberships: [{ family: 'pink', order: 87 }] },
  'LC-119': { code: 'LC-119', source: 'languo', memberships: [{ family: 'pink', order: 101 }, { family: 'red', order: 44 }] },
  'LC-191': { code: 'LC-191', source: 'languo', memberships: [{ family: 'white-grey-black', order: 3 }, { family: 'yellow', order: 0.5 }] },
  'LC-192': { code: 'LC-192', source: 'languo', memberships: [{ family: 'white-grey-black', order: 17 }, { family: 'green', order: 2 }] },
  'LC-193': { code: 'LC-193', source: 'languo', memberships: [{ family: 'white-grey-black', order: 13 }, { family: 'green', order: 1 }] },
  'LC-194': { code: 'LC-194', source: 'languo', memberships: [{ family: 'white-grey-black', order: 14 }, { family: 'blue', order: 2 }] },
  'LC-195': { code: 'LC-195', source: 'languo', memberships: [{ family: 'white-grey-black', order: 8 }, { family: 'pink', order: 1 }] },
  'LC-196': { code: 'LC-196', source: 'languo', memberships: [{ family: 'white-grey-black', order: 15 }, { family: 'pink', order: 3 }] },
  'LC-197': { code: 'LC-197', source: 'languo', memberships: [{ family: 'white-grey-black', order: 7 }, { family: 'orange', order: 2 }, { family: 'yellow', order: 2 }] },
  'LC-198': { code: 'LC-198', source: 'languo', memberships: [{ family: 'white-grey-black', order: 5 }] },
  'LC-199': { code: 'LC-199', source: 'languo', memberships: [{ family: 'white-grey-black', order: 11 }] },
  'PC-233': { code: 'PC-233', source: 'languo', memberships: [{ family: 'pink', order: 13 }] },
  'PC-234': { code: 'PC-234', source: 'languo', memberships: [{ family: 'pink', order: 27 }] },
  'PC-235': { code: 'PC-235', source: 'languo', memberships: [{ family: 'pink', order: 20 }] },
  'PC-236': { code: 'PC-236', source: 'languo', memberships: [{ family: 'pink', order: 56 }] },
  'PC-237': { code: 'PC-237', source: 'languo', memberships: [{ family: 'pink', order: 63 }] },
  'PC-238': { code: 'PC-238', source: 'languo', memberships: [{ family: 'pink', order: 57 }] },
  'PC-239': { code: 'PC-239', source: 'languo', memberships: [{ family: 'pink', order: 84 }] },
  'PC-240': { code: 'PC-240', source: 'languo', memberships: [{ family: 'pink', order: 89 }] },
  'PC-241': { code: 'PC-241', source: 'languo', memberships: [{ family: 'pink', order: 107 }] },
  'PC-242': { code: 'PC-242', source: 'languo', memberships: [{ family: 'pink', order: 109 }] },
  'PC-243': { code: 'PC-243', source: 'languo', memberships: [{ family: 'pink', order: 92 }] },
  'PC-244': { code: 'PC-244', source: 'languo', memberships: [{ family: 'pink', order: 40 }] },
  'PC-801': { code: 'PC-801', source: 'languo', memberships: [{ family: 'pink', order: 8 }] },
  'PC-802': { code: 'PC-802', source: 'languo', memberships: [{ family: 'pink', order: 37 }] },
  'PC-803': { code: 'PC-803', source: 'languo', memberships: [{ family: 'pink', order: 46 }] },
  'PC-804': { code: 'PC-804', source: 'languo', memberships: [{ family: 'pink', order: 64 }] },
  'PC-805': { code: 'PC-805', source: 'languo', memberships: [{ family: 'pink', order: 96 }] },
  'PC-806': { code: 'PC-806', source: 'languo', memberships: [{ family: 'pink', order: 94 }] },
  'PC-807': { code: 'PC-807', source: 'languo', memberships: [{ family: 'pink', order: 97 }] },
  'PC-808': { code: 'PC-808', source: 'languo', memberships: [{ family: 'pink', order: 105 }] },
  'PC-809': { code: 'PC-809', source: 'languo', memberships: [{ family: 'pink', order: 113 }] },
  'PC-810': { code: 'PC-810', source: 'languo', memberships: [{ family: 'pink', order: 6 }] },
  'PC-811': { code: 'PC-811', source: 'languo', memberships: [{ family: 'pink', order: 58 }] },
  'PC-812': { code: 'PC-812', source: 'languo', memberships: [{ family: 'pink', order: 79 }] },
  'PC-813': { code: 'PC-813', source: 'languo', memberships: [{ family: 'pink', order: 98 }] },
  'PC-814': { code: 'PC-814', source: 'languo', memberships: [{ family: 'pink', order: 70 }] },
  'PC-815': { code: 'PC-815', source: 'languo', memberships: [{ family: 'pink', order: 104 }] },
  'PC-816': { code: 'PC-816', source: 'languo', memberships: [{ family: 'pink', order: 83 }] },
  'PC-817': { code: 'PC-817', source: 'languo', memberships: [{ family: 'pink', order: 45 }] },
  'PC-818': { code: 'PC-818', source: 'languo', memberships: [{ family: 'pink', order: 99 }] },
  'PU-301': { code: 'PU-301', source: 'languo', memberships: [{ family: 'violet-purple', order: 4 }] },
  'PU-302': { code: 'PU-302', source: 'languo', memberships: [{ family: 'violet-purple', order: 16 }] },
  'PU-303': { code: 'PU-303', source: 'languo', memberships: [{ family: 'violet-purple', order: 33 }] },
  'PU-304': { code: 'PU-304', source: 'languo', memberships: [{ family: 'violet-purple', order: 51 }] },
  'PU-305': { code: 'PU-305', source: 'languo', memberships: [{ family: 'violet-purple', order: 60 }] },
  'PU-306': { code: 'PU-306', source: 'languo', memberships: [{ family: 'violet-purple', order: 52 }] },
  'PU-307': { code: 'PU-307', source: 'languo', memberships: [{ family: 'violet-purple', order: 43 }] },
  'PU-308': { code: 'PU-308', source: 'languo', memberships: [{ family: 'violet-purple', order: 41 }] },
  'PU-309': { code: 'PU-309', source: 'languo', memberships: [{ family: 'pink', order: 38 }, { family: 'violet-purple', order: 22 }] },
  'PU-310': { code: 'PU-310', source: 'languo', memberships: [{ family: 'violet-purple', order: 3 }] },
  'PU-311': { code: 'PU-311', source: 'languo', memberships: [{ family: 'violet-purple', order: 1 }] },
  'PU-312': { code: 'PU-312', source: 'languo', memberships: [{ family: 'violet-purple', order: 15 }] },
  'PU-313': { code: 'PU-313', source: 'languo', memberships: [{ family: 'violet-purple', order: 21 }] },
  'PU-314': { code: 'PU-314', source: 'languo', memberships: [{ family: 'violet-purple', order: 47 }] },
  'PU-315': { code: 'PU-315', source: 'languo', memberships: [{ family: 'violet-purple', order: 63 }] },
  'PU-316': { code: 'PU-316', source: 'languo', memberships: [{ family: 'violet-purple', order: 12 }] },
  'PU-317': { code: 'PU-317', source: 'languo', memberships: [{ family: 'violet-purple', order: 14 }] },
  'PU-318': { code: 'PU-318', source: 'languo', memberships: [{ family: 'violet-purple', order: 29 }] },
  'PU-319': { code: 'PU-319', source: 'languo', memberships: [{ family: 'violet-purple', order: 56 }] },
  'PU-320': { code: 'PU-320', source: 'languo', memberships: [{ family: 'violet-purple', order: 54 }] },
  'PU-321': { code: 'PU-321', source: 'languo', memberships: [{ family: 'violet-purple', order: 24 }] },
  'RY-01': { code: 'RY-01', source: 'languo', memberships: [{ family: 'yellow', order: 12 }] },
  'RY-02': { code: 'RY-02', source: 'languo', memberships: [{ family: 'yellow', order: 26 }] },
  'RY-03': { code: 'RY-03', source: 'languo', memberships: [{ family: 'yellow', order: 35 }] },
  'RY-04': { code: 'RY-04', source: 'languo', memberships: [{ family: 'orange', order: 39 }, { family: 'red', order: 18.25 }] },
  'RY-05': { code: 'RY-05', source: 'languo', memberships: [{ family: 'red', order: 27 }] },
  'RY-06': { code: 'RY-06', source: 'languo', memberships: [{ family: 'red', order: 30 }] },
  'RY-07': { code: 'RY-07', source: 'languo', memberships: [{ family: 'brown', order: 111 }, { family: 'red', order: 53 }] },
  'RY-08': { code: 'RY-08', source: 'languo', memberships: [{ family: 'brown', order: 112 }, { family: 'red', order: 54 }] },
  'RY-09': { code: 'RY-09', source: 'languo', memberships: [{ family: 'brown', order: 89 }, { family: 'red', order: 48 }] },
  'RY-10': { code: 'RY-10', source: 'languo', memberships: [{ family: 'red', order: 23 }] },
  'RY-11': { code: 'RY-11', source: 'languo', memberships: [{ family: 'red', order: 25 }] },
  'RY-12': { code: 'RY-12', source: 'languo', memberships: [{ family: 'red', order: 38 }] },
  'RY-13': { code: 'RY-13', source: 'languo', memberships: [{ family: 'brown', order: 90 }, { family: 'red', order: 49 }] },
  'RY-14': { code: 'RY-14', source: 'languo', memberships: [{ family: 'brown', order: 113 }, { family: 'red', order: 55 }] },
  'RY-15': { code: 'RY-15', source: 'languo', memberships: [{ family: 'red', order: 21 }, { family: 'orange', order: 47 }] },
  'SG-151': { code: 'SG-151', source: 'languo', memberships: [{ family: 'green', order: 12 }] },
  'SG-152': { code: 'SG-152', source: 'languo', memberships: [{ family: 'green', order: 17 }] },
  'SG-153': { code: 'SG-153', source: 'languo', memberships: [{ family: 'green', order: 48 }] },
  'SG-154': { code: 'SG-154', source: 'languo', memberships: [{ family: 'green', order: 83 }] },
  'SG-155': { code: 'SG-155', source: 'languo', memberships: [{ family: 'green', order: 73 }] },
  'SG-156': { code: 'SG-156', source: 'languo', memberships: [{ family: 'green', order: 75 }] },
  'SG-157': { code: 'SG-157', source: 'languo', memberships: [{ family: 'green', order: 122 }] },
  'SG-158': { code: 'SG-158', source: 'languo', memberships: [{ family: 'green', order: 124 }] },
  'SG-159': { code: 'SG-159', source: 'languo', memberships: [{ family: 'green', order: 126 }] },
  'SG-221': { code: 'SG-221', source: 'languo', memberships: [{ family: 'green', order: 28 }] },
  'SG-222': { code: 'SG-222', source: 'languo', memberships: [{ family: 'green', order: 45 }] },
  'SG-223': { code: 'SG-223', source: 'languo', memberships: [{ family: 'green', order: 49 }] },
  'SG-224': { code: 'SG-224', source: 'languo', memberships: [{ family: 'green', order: 27 }] },
  'SG-225': { code: 'SG-225', source: 'languo', memberships: [{ family: 'green', order: 23 }] },
  'SG-226': { code: 'SG-226', source: 'languo', memberships: [{ family: 'green', order: 59 }] },
  'SG-227': { code: 'SG-227', source: 'languo', memberships: [{ family: 'green', order: 70 }] },
  'SG-228': { code: 'SG-228', source: 'languo', memberships: [{ family: 'green', order: 89 }] },
  'SG-229': { code: 'SG-229', source: 'languo', memberships: [{ family: 'green', order: 68 }] },
  'SG-230': { code: 'SG-230', source: 'languo', memberships: [{ family: 'green', order: 92 }] },
  'SG-231': { code: 'SG-231', source: 'languo', memberships: [{ family: 'green', order: 101 }] },
  'SG-232': { code: 'SG-232', source: 'languo', memberships: [{ family: 'green', order: 108 }] },
  'YE-121': { code: 'YE-121', source: 'languo', memberships: [{ family: 'yellow', order: 16 }] },
  'YE-1210': { code: 'YE-1210', source: 'languo', memberships: [{ family: 'yellow', order: 37 }] },
  'YE-1211': { code: 'YE-1211', source: 'languo', memberships: [{ family: 'yellow', order: 49 }] },
  'YE-1212': { code: 'YE-1212', source: 'languo', memberships: [{ family: 'yellow', order: 61 }] },
  'YE-122': { code: 'YE-122', source: 'languo', memberships: [{ family: 'yellow', order: 21 }] },
  'YE-123': { code: 'YE-123', source: 'languo', memberships: [{ family: 'yellow', order: 27 }] },
  'YE-124': { code: 'YE-124', source: 'languo', memberships: [{ family: 'yellow', order: 34 }] },
  'YE-125': { code: 'YE-125', source: 'languo', memberships: [{ family: 'yellow', order: 53 }] },
  'YE-126': { code: 'YE-126', source: 'languo', memberships: [{ family: 'yellow', order: 56 }] },
  'YE-127': { code: 'YE-127', source: 'languo', memberships: [{ family: 'yellow', order: 58 }] },
  'YE-128': { code: 'YE-128', source: 'languo', memberships: [{ family: 'yellow', order: 50 }] },
  'YE-129': { code: 'YE-129', source: 'languo', memberships: [{ family: 'yellow', order: 40 }] },
  'YE-130': { code: 'YE-130', source: 'languo', memberships: [{ family: 'yellow', order: 11 }] },
  'YE-131': { code: 'YE-131', source: 'languo', memberships: [{ family: 'yellow', order: 9 }] },
  'YE-132': { code: 'YE-132', source: 'languo', memberships: [{ family: 'yellow', order: 18 }] },
  'YE-133': { code: 'YE-133', source: 'languo', memberships: [{ family: 'yellow', order: 43 }] },
  'YE-134': { code: 'YE-134', source: 'languo', memberships: [{ family: 'yellow', order: 29 }] },
  'YE-135': { code: 'YE-135', source: 'languo', memberships: [{ family: 'yellow', order: 30 }] },
  'YE-136': { code: 'YE-136', source: 'languo', memberships: [{ family: 'yellow', order: 55 }] },
};

export function getFamilyMemberships(code: string): FamilyMembership[] {
  return COLOR_FAMILIES[code]?.memberships ?? [];
}

// Returns every code in a family, sorted by the curated light-to-dark order
// for that specific family (a code's order can differ between the families
// it belongs to).
export function getCodesInFamily(family: ColorFamily): string[] {
  return Object.values(COLOR_FAMILIES)
    .map((entry) => {
      const m = entry.memberships.find((mm) => mm.family === family);
      return m ? { code: entry.code, order: m.order } : null;
    })
    .filter((x): x is { code: string; order: number } => x !== null)
    .sort((a, b) => a.order - b.order)
    .map((x) => x.code);
}
